Fix overly large image header
centre-for-effective-altruism/centreforeffectivealtruism-org pull request #6
Opened 2018-05-19 21:17 UTC by jpaddison3

2018-05-21 21:14 UTC, colophonemes requested changes
Sorry, but big headers are dope and cool and I don't think you've thought sufficiently about how totally sweet they look. Props for taking the initiative on this though.

2018-05-21 21:14 UTC, colophonemes commented on src/styles/partials/layout/_header.scss
> -	height: 70vh;
Can we put the `vh`-specified height back. I'm happy with:

```sass
#header {
	...
	height: 50vh;
	@media(min-width: $screen-lg) {
		height: 40vh;
	}
}
```

2018-05-21 21:14 UTC, colophonemes commented on src/layouts/layout/header.pug
> +			.col-xs-8.col-xs-offset-2.col-sm-3.col-sm-offset-4
This makes the logo tiny at `sm` and `md` breakpoints. I'd revert this.

2018-05-30 16:40 UTC, jpaddison3 commented
Ready for another review @colophonemes

2018-06-05 22:49 UTC, colophonemes approved these changes
LGTM

2018-06-05 23:45 UTC, merged